version: 0.0 # required as per aws codedeploy to be 0.0
os: linux
files:
  - source: /
    destination: ~/app
permissions:
  - object: ~/app
    owner: ubuntu
    group: ubuntu
    type:
        - directory
        - file
hooks:
  AfterInstall:
    - location: ./.scripts/after-install.sh
      runas: ubuntu
  ApplicationStart:
    - location: ./.scripts/application-start.sh
      runas: ubuntuk