name: deploy

# on:
#   workflow_run:
#     workflows:
#       - checks
#     types:
#       - completed
#     branches:
#       - "**"
#       - "main"

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
    env:
      REMOTE_USER: ${{ SECRETS.STAGE_USER }}
      REMOTE_HOST: ${{ SECRETS.STAGE_HOST }}
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - name: setup ssh key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ SECRETS.STAGE_SSH_KEY }}
          name: stage_key
          known_hosts: ${{ SECRETS.STAGE_KNOWN_HOSTS }}
      - name: setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: restore cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: build
        run: npm run build:docker
      - name: package image
        run: npm run docker:package
      - name: deploy
        run: npm run deploy:stage